---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - 'eval $(curl https://travis-perl.github.io/init) --auto'
  - 'cpanm Code::TidyAll::Plugin::SortLines::Naturally'
  - 'cpanm Code::TidyAll::Plugin::UniqueLines'
  - 'cpanm Perl::Tidy'
cache:
  directories:
    - local
    - '~/perl5'
language: perl
matrix:
  include:
    -
      env: COVERAGE=1
      perl: '5.26'
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - olaf@wundersolutions.com
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
sudo: 'false'
